requestRouter:
  port: 9091
  name: prestoRouter
  historySize: 1000

dataStore:
  jdbcUrl: jdbc:mysql://xxx.xxx.xxx.xxx:3306/prestogateway
  user: root
  password: root123456abc
  driver: com.mysql.cj.jdbc.Driver

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

notifier:
  smtpHost: localhost
  smtpPort: 587
  sender: fanglu@wish.com
  recipients:
    - fanglu@wish.com

modules:
  - com.lyft.data.gateway.ha.module.HaGatewayProviderModule

managedApps:
  - com.lyft.data.gateway.ha.GatewayManagedApp

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.lyft: DEBUG

  appenders:
    - type: console
    - type: file
      currentLogFilename: /var/log/prestoproxy/prestoproxy-java.log
      archivedLogFilenamePattern: /var/log/prestoproxy/prestoproxy-java-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 100MB
